const GK = { id: 'gk', label: 'ARQ', x: 50, y: 88 }

function backFour() {
  return [
    { id: 'lb', label: 'LI', x: 15, y: 68 },
    { id: 'cb1', label: 'DFC', x: 35, y: 72 },
    { id: 'cb2', label: 'DFC', x: 65, y: 72 },
    { id: 'rb', label: 'LD', x: 85, y: 68 },
  ]
}

function backThree() {
  return [
    { id: 'cb1', label: 'DFC', x: 25, y: 72 },
    { id: 'cb2', label: 'DFC', x: 50, y: 75 },
    { id: 'cb3', label: 'DFC', x: 75, y: 72 },
  ]
}

function backFive() {
  return [
    { id: 'lwb', label: 'LI', x: 10, y: 62 },
    { id: 'cb1', label: 'DFC', x: 30, y: 72 },
    { id: 'cb2', label: 'DFC', x: 50, y: 75 },
    { id: 'cb3', label: 'DFC', x: 70, y: 72 },
    { id: 'rwb', label: 'LD', x: 90, y: 62 },
  ]
}

export const FORMATIONS = {
  '4-3-3': [GK, ...backFour(),
    { id: 'cm1', label: 'MC', x: 30, y: 48 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 48 },
    { id: 'lw', label: 'EI', x: 18, y: 22 },
    { id: 'st', label: 'DC', x: 50, y: 15 },
    { id: 'rw', label: 'ED', x: 82, y: 22 },
  ],
  '4-4-2': [GK, ...backFour(),
    { id: 'lm', label: 'MI', x: 15, y: 42 },
    { id: 'cm1', label: 'MC', x: 38, y: 48 },
    { id: 'cm2', label: 'MC', x: 62, y: 48 },
    { id: 'rm', label: 'MD', x: 85, y: 42 },
    { id: 'st1', label: 'DC', x: 38, y: 18 },
    { id: 'st2', label: 'DC', x: 62, y: 18 },
  ],
  '4-2-3-1': [GK, ...backFour(),
    { id: 'cdm1', label: 'MCD', x: 38, y: 52 },
    { id: 'cdm2', label: 'MCD', x: 62, y: 52 },
    { id: 'cam', label: 'MCO', x: 50, y: 35 },
    { id: 'lw', label: 'EI', x: 18, y: 22 },
    { id: 'rw', label: 'ED', x: 82, y: 22 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
  ],
  '4-3-1-2': [GK, ...backFour(),
    { id: 'cm1', label: 'MC', x: 30, y: 48 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 48 },
    { id: 'cam', label: 'MCO', x: 50, y: 30 },
    { id: 'st1', label: 'DC', x: 38, y: 15 },
    { id: 'st2', label: 'DC', x: 62, y: 15 },
  ],
  '4-1-4-1': [GK, ...backFour(),
    { id: 'cdm', label: 'MCD', x: 50, y: 55 },
    { id: 'lm', label: 'MI', x: 15, y: 40 },
    { id: 'cm1', label: 'MC', x: 38, y: 45 },
    { id: 'cm2', label: 'MC', x: 62, y: 45 },
    { id: 'rm', label: 'MD', x: 85, y: 40 },
    { id: 'st', label: 'DC', x: 50, y: 14 },
  ],
  '4-4-1-1': [GK, ...backFour(),
    { id: 'lm', label: 'MI', x: 15, y: 42 },
    { id: 'cm1', label: 'MC', x: 38, y: 48 },
    { id: 'cm2', label: 'MC', x: 62, y: 48 },
    { id: 'rm', label: 'MD', x: 85, y: 42 },
    { id: 'cam', label: 'MCO', x: 50, y: 28 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
  ],
  '4-5-1': [GK, ...backFour(),
    { id: 'lm', label: 'MI', x: 12, y: 45 },
    { id: 'cm1', label: 'MC', x: 30, y: 48 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 48 },
    { id: 'rm', label: 'MD', x: 88, y: 45 },
    { id: 'st', label: 'DC', x: 50, y: 14 },
  ],
  '3-5-2': [GK, ...backThree(),
    { id: 'lwb', label: 'CAI', x: 12, y: 48 },
    { id: 'cdm', label: 'MCD', x: 50, y: 52 },
    { id: 'rwb', label: 'CAD', x: 88, y: 48 },
    { id: 'cm1', label: 'MC', x: 35, y: 38 },
    { id: 'cm2', label: 'MC', x: 65, y: 38 },
    { id: 'st1', label: 'DC', x: 38, y: 15 },
    { id: 'st2', label: 'DC', x: 62, y: 15 },
  ],
  '3-4-3': [GK, ...backThree(),
    { id: 'lm', label: 'MI', x: 15, y: 45 },
    { id: 'cm1', label: 'MC', x: 38, y: 48 },
    { id: 'cm2', label: 'MC', x: 62, y: 48 },
    { id: 'rm', label: 'MD', x: 85, y: 45 },
    { id: 'lw', label: 'EI', x: 22, y: 20 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
    { id: 'rw', label: 'ED', x: 78, y: 20 },
  ],
  '3-4-2-1': [GK, ...backThree(),
    { id: 'lm', label: 'MI', x: 15, y: 45 },
    { id: 'cm1', label: 'MC', x: 38, y: 48 },
    { id: 'cm2', label: 'MC', x: 62, y: 48 },
    { id: 'rm', label: 'MD', x: 85, y: 45 },
    { id: 'cam1', label: 'MCO', x: 35, y: 28 },
    { id: 'cam2', label: 'MCO', x: 65, y: 28 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
  ],
  '3-4-1-2': [GK, ...backThree(),
    { id: 'lm', label: 'MI', x: 15, y: 45 },
    { id: 'cm1', label: 'MC', x: 38, y: 48 },
    { id: 'cm2', label: 'MC', x: 62, y: 48 },
    { id: 'rm', label: 'MD', x: 85, y: 45 },
    { id: 'cam', label: 'MCO', x: 50, y: 30 },
    { id: 'st1', label: 'DC', x: 38, y: 14 },
    { id: 'st2', label: 'DC', x: 62, y: 14 },
  ],
  '3-6-1': [GK, ...backThree(),
    { id: 'lm', label: 'MI', x: 10, y: 48 },
    { id: 'cm1', label: 'MC', x: 26, y: 45 },
    { id: 'cm2', label: 'MC', x: 42, y: 42 },
    { id: 'cm3', label: 'MC', x: 58, y: 42 },
    { id: 'cm4', label: 'MC', x: 74, y: 45 },
    { id: 'rm', label: 'MD', x: 90, y: 48 },
    { id: 'st', label: 'DC', x: 50, y: 14 },
  ],
  '3-3-1-3': [GK, ...backThree(),
    { id: 'cm1', label: 'MC', x: 30, y: 48 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 48 },
    { id: 'cam', label: 'MCO', x: 50, y: 30 },
    { id: 'lw', label: 'EI', x: 20, y: 18 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
    { id: 'rw', label: 'ED', x: 80, y: 18 },
  ],
  '5-3-2': [GK, ...backFive(),
    { id: 'cm1', label: 'MC', x: 30, y: 45 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 45 },
    { id: 'st1', label: 'DC', x: 38, y: 15 },
    { id: 'st2', label: 'DC', x: 62, y: 15 },
  ],
  '5-4-1': [GK, ...backFive(),
    { id: 'lm', label: 'MI', x: 18, y: 42 },
    { id: 'cm1', label: 'MC', x: 40, y: 45 },
    { id: 'cm2', label: 'MC', x: 60, y: 45 },
    { id: 'rm', label: 'MD', x: 82, y: 42 },
    { id: 'st', label: 'DC', x: 50, y: 14 },
  ],
  '5-2-3': [GK, ...backFive(),
    { id: 'cdm1', label: 'MCD', x: 38, y: 50 },
    { id: 'cdm2', label: 'MCD', x: 62, y: 50 },
    { id: 'lw', label: 'EI', x: 20, y: 20 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
    { id: 'rw', label: 'ED', x: 80, y: 20 },
  ],
  '4-2-2-2': [GK, ...backFour(),
    { id: 'cdm1', label: 'MCD', x: 38, y: 52 },
    { id: 'cdm2', label: 'MCD', x: 62, y: 52 },
    { id: 'cam1', label: 'MCO', x: 38, y: 32 },
    { id: 'cam2', label: 'MCO', x: 62, y: 32 },
    { id: 'st1', label: 'DC', x: 38, y: 14 },
    { id: 'st2', label: 'DC', x: 62, y: 14 },
  ],
  '4-2-4': [GK, ...backFour(),
    { id: 'cdm1', label: 'MCD', x: 38, y: 52 },
    { id: 'cdm2', label: 'MCD', x: 62, y: 52 },
    { id: 'lw', label: 'EI', x: 18, y: 22 },
    { id: 'st1', label: 'DC', x: 38, y: 15 },
    { id: 'st2', label: 'DC', x: 62, y: 15 },
    { id: 'rw', label: 'ED', x: 82, y: 22 },
  ],
  '4-1-2-3': [GK, ...backFour(),
    { id: 'cdm', label: 'MCD', x: 50, y: 55 },
    { id: 'cm1', label: 'MC', x: 35, y: 42 },
    { id: 'cm2', label: 'MC', x: 65, y: 42 },
    { id: 'lw', label: 'EI', x: 20, y: 20 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
    { id: 'rw', label: 'ED', x: 80, y: 20 },
  ],
  '4-3-2-1': [GK, ...backFour(),
    { id: 'cm1', label: 'MC', x: 30, y: 48 },
    { id: 'cm2', label: 'MC', x: 50, y: 42 },
    { id: 'cm3', label: 'MC', x: 70, y: 48 },
    { id: 'cam1', label: 'MCO', x: 35, y: 28 },
    { id: 'cam2', label: 'MCO', x: 65, y: 28 },
    { id: 'st', label: 'DC', x: 50, y: 12 },
  ],
  '4-1-3-2': [GK, ...backFour(),
    { id: 'cdm', label: 'MCD', x: 50, y: 55 },
    { id: 'cm1', label: 'MC', x: 30, y: 42 },
    { id: 'cm2', label: 'MC', x: 50, y: 38 },
    { id: 'cm3', label: 'MC', x: 70, y: 42 },
    { id: 'st1', label: 'DC', x: 38, y: 14 },
    { id: 'st2', label: 'DC', x: 62, y: 14 },
  ],
}

export const FORMATION_NAMES = Object.keys(FORMATIONS)

export function getFormationSlots(formation, customFormations = {}) {
  if (customFormations[formation]) {
    return customFormations[formation].slots
  }
  return FORMATIONS[formation] ?? FORMATIONS['4-3-3']
}

export function createEmptyLineup(formation, customFormations = {}) {
  const lineup = {}
  getFormationSlots(formation, customFormations).forEach((slot) => {
    lineup[slot.id] = null
  })
  return lineup
}

export function getAllFormationOptions(customFormations = {}) {
  const builtIn = FORMATION_NAMES.map((name) => ({ value: name, label: name, custom: false }))
  const custom = Object.values(customFormations).map((formation) => ({
    value: formation.id,
    label: formation.name,
    custom: true,
  }))
  return [...builtIn, ...custom]
}
